# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ## Directives to enable stock and custom task list includes
      ## Called via include_tasks from chromebook_setup.yml
      ## For custom includes, corresponding stock include must be enabled
      debian_base_include: true
      debian_base_custom_include: "{{ ansible_config }}includes_custom/debian_base/debian_base_custom.yml"
      gcloud_include: true
      gcloud_custom_include: "{{ ansible_config }}includes_custom/gcloud/gcloud_custom.yml"
      vscode_include: true
      vscode_custom_include: "{{ ansible_config }}includes_custom/vscode/vscode_custom.yml"
      terraform_include: true
      # terraform_custom_include:
      docker_include: true
      # docker_custom_include:
      gimp_include: true
      # gimp_custom_include:
      master_pdf_include: true
      # master_pdf_custom_include:
      user_defined_custom_include: "{{ ansible_config }}includes_custom/user_defined/user_defined.yml"

    ## You can use the same config repo to manage multiple systems
    ## Give each system an entry like the example below
    ## if you would like to have different configuration per host.
    # my_chromebook.local:
    #   ansible_connection: local
    #   ansible_python_interpreter: /usr/bin/python3
    #   ## Directives to enable stock and custom task list includes
    #   ## Called via include_tasks from chromebook_setup.yml
    #   ## For custom includes, corresponding stock include must be enabled
    #   debian_base_include: true
    #   debian_base_custom_include: "{{ ansible_config }}includes_custom/debian_base/debian_base_custom.yml"
    #   gcloud_include: true
    #   gcloud_custom_include: "{{ ansible_config }}includes_custom/gcloud/gcloud_custom.yml"
    #   vscode_include: true
    #   vscode_custom_include: "{{ ansible_config }}includes_custom/vscode/vscode_custom.yml"
    #   terraform_include: true
    #   # terraform_custom_include:
    #   docker_include: true
    #   # docker_custom_include:
    #   gimp_include: true
    #   # gimp_custom_include:
    #   master_pdf_include: true
    #   # master_pdf_custom_include:
    #   user_defined_custom_include: "{{ ansible_config }}includes_custom/user_defined/user_defined.yml"
      
       
      
      
      


 